services:
  # TODO: add cronjob to restart it every day
  selenium-chrome-node:
    networks: [dfc]
    image: selenium/node-chrome:4.8.3-20230403
    restart: unless-stopped
    environment:
      SE_EVENT_BUS_HOST: "selenium-hub"
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    tmpfs:
      - /dev/shm:size=1024m
    volumes:
      # TODO: clear this directory daily + set permissions - see k8s template
      - /tmp/selenium-tempdata:/var/selenium/tempdata

  selenium-chrome-node-cleanup:
    x-cronjob:
      schedule: "10 1 * * *"
    networks: [dfc]
    image: docker:25@sha256:915cd1624f521b6337f135075f712c8fb14c0b151595c6144d7ce05d2f257869
    entrypoint:
      - sh
      - -c
      - |
        docker stop selenium-selenium-chrome-node-1 selenium-selenium-chrome-node-nginx-1
        rm -rf /var/selenium/tempdata/*
        rm -rf /var/selenium/tempdata/.*
        docker start selenium-selenium-chrome-node-1 selenium-selenium-chrome-node-nginx-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/selenium-tempdata:/var/selenium/tempdata

  selenium-chrome-node-nginx:
    networks: [dfc]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.selenium-chrome-node-nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.selenium-chrome-node-nginx.rule=Host(`selenium.dfc2.dataforchange.org.il`)"
      - "traefik.http.routers.selenium-chrome-node-nginx.middlewares=selenium-auth@file"
    image: nginx@sha256:63b44e8ddb83d5dd8020327c1f40436e37a6fffd3ef2498a6204df23be6e7e94
    restart: unless-stopped
    volumes:
      - /tmp/selenium-tempdata:/var/selenium/tempdata
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./setuser.sh:/docker-entrypoint.d/99-setuser.sh:ro

  selenium-hub:
    networks: [dfc]
    image: selenium/hub:4.8.3-20230403
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.selenium-hub.loadbalancer.server.port=4444"
      - "traefik.http.routers.selenium-hub.rule=Host(`selenium-hub.dfc2.dataforchange.org.il`)"
      - "traefik.http.routers.selenium-hub.middlewares=selenium-auth@file"

networks:
  dfc:
    external: true

x-on-file-change:
  - "nginx-default.conf": docker compose restart selenium-chrome-node-nginx
  - "setuser.sh": docker compose restart selenium-chrome-node-nginx

x-files:
  nginx-default.conf: {}
  setuser.sh: {}
